export * from './user';
export * from './college';
export * from './deparment';
export * from './program';
export * from './subprogram';
export * from './subject';
export * from './faculty';
export * from './student';
export * from './timetable';
