import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { NavbarDemo } from "./components/NavbarDemo";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart-ClassRoom and Timetable-Schedular",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}
      >
        <AuthProvider>
          {/* Navbar always on top */}
          <div className="relative z-16 pointer-events-auto">
            <NavbarDemo />
          </div>

          {/* Main content stays above background */}
          <main className="min-h-screen p-4 relative z-10">
            {children}
          </main>

          {/* Footer with highest priority */}
          <footer className="relative z-20 pointer-events-auto">
            <Footer />
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
